title: "ACCESS: An optical transmission spectrum of the high gravity, hot Jupiter HAT-P-23b"

logo: images/access.png

only_build_toc_files: true

execute:
  execute_notebooks: off

exclude_patterns: [".git*", _build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", notebooks/__pycache__/, notebooks/data, notebooks/utils.py]

html:
  use_repository_button: true
  extra_navbar: ""

launch_buttons:
  binderhub_url: ""

repository:
  url: https://github.com/icweaver/HAT-P-23b
